[package]
name = "canvas_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
itertools = "0.11.0"
paste = "1.0.14"
thiserror = "1.0.40"
yansi = "0.5.1"
